from Modules.Utilities import Assets

config_data = {
            "theme": "darkly",
            "custom_themes": True,
            "clock_mode": "45min 10min",
            "reminder_activation": 5,
            "starting_page": 0,
            "end_of_lesson_reminder": True,
            "enable_top_theme_selector": True,
            "enable_primary_notifier": True,
            "enable_secondary_notifier": True,
            "enable_progress_bar": True,
            "current_page": 0,
            "high_dpi_mode": True,
            "browser": "chrome",
            "number_of_lessons": Assets.default_number_of_lessons,
            "image_locations": [Assets.default_image_locations for _ in range(13)],
            "program_locations": ["default" for _ in range(13)],
            "program_names": [f"Button_{i}" for i in range(13)],
            "project_output_locations": [],
            "project_names": [],
            "file_backup_names": [],
            "file_backup_locations": [],
            "preset_name": [],
            "preset_source": [],
            "preset_destination": [],
            "preset_application_location": [],
        }
