config_data = {
            "theme": "",
            "custom_themes": True,
            "clock_mode": "",
            "reminder_activation": 5,
            "starting_page": 0,
            "end_of_lesson_reminder": True,
            "enable_top_theme_selector": True,
            "enable_primary_notifier": True,
            "enable_secondary_notifier": True,
            "enable_progress_bar": True,
            "current_page": 0,
            "browser": "chrome",
            "number_of_lessons": [],
            "image_locations": [],
            "program_locations": [],
            "program_names": [],
            "project_output_locations": [],
            "project_names": [],
            "file_backup_names": [],
            "file_backup_locations": [],
            "preset_name": [],
            "preset_source": [],
            "preset_destination": [],
            "preset_application_location": [],
        }