config_data = {
            "theme": "",
            "custom_themes": True,
            "clock_mode": "",
            "reminder_activation": 5,
            "starting_page": 0,
            "end_of_lesson_reminder": True,
            "enable_top_theme_selector": True,
            "enable_primary_notifier": True,
            "enable_secondary_notifier": True,
            "enable_progress_bar": True,
            "current_page": 0,
            "browser": "google",
            "show_files_being_copied_in_cmd": 1,
            "number_of_lessons": [],
            "image_locations": [],
            "program_locations": [],
            "program_names": [],
            "file_output_locations": [],
            "file_backup_names": [],
            "file_backup_locations": [],
            "preset_name": [],
            "preset_input": [],
            "preset_output": [],
            "preset_application_location": [],
        }